config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  resources :feedbacks

  get 'search/show'

  get 'profile/own' # must stand above the resources for profile
  post 'profile/search'
  post 'profile/contact'
  resources :profile

  get 'recommendations/show'

  devise_for :users

  get 'sessions/new', as: :login
  get 'sessions/destroy', as: :logout

  mount Mercury::Engine => '/'
  Mercury::Engine.routes

  post 'articles/search'
  resources :articles do
    member { put :mercury_update}
    member { post :rate }
    member { post :rate_comment }
    resources :comments
  end

end

app/models/comment.rb
class Comment
  include Neo4j::ActiveNode
  property :body, type: String
  property :pos_neg, type: Boolean

  property :created_at, type: DateTime
  # property :created_on, type: Date

  property :updated_at, type: DateTime
  # property :updated_on, type: Date

  # The following fields are redundant and only there for performance reasons
  property :standard_deviation, type: Float
  property :popularity, type: Float
  property :recommender_value, type: Float

  has_many :in, :ratings, unique: true, rel_class: Rating, model_class: User
  has_one :out, :article, type: :comment_on
  has_one :in, :author, unique: true, type: :authored, model_class: User

  has_many :out, :children, model_class: Comment, unique: true
  has_one :in, :child_of, model_class: Comment, unique: true, type: :children

  validates_length_of :body, within: 10..1000, too_long: ' is too long (max. 1000 letters)',
                      too_short: 'is too short. Provide more arguments please.'

  def get_number_of_replies
    result = 0
    unless children.count == 0
      result += children.count
      children.each do |child|
        result += child.get_number_of_replies
      end
    end
    result
  end

  # noinspection RubyInstanceMethodNamingConvention
  def get_standard_deviation_of_ratings
    comment_id = self.id
    query = Neo4j::Session.query.
        match("()-[rating:`rates`]->(this)").
        where("this.uuid = '#{comment_id}'").
        return("stdevp(rating.value)")
    self.standard_deviation =  query.first.first
  end

  def get_average_rating
    comment_id = self.id
    query = Neo4j::Session.query.
      match("()-[rating:`rates`]->(this)").
      where("this.uuid = '#{comment_id}'").
      return("avg(rating.value)")
    query.first.first
  end

  def get_popularity
    self.popularity = Math.log get_number_of_ratings, 10 # base = 10
  end

  def get_number_of_ratings(ratings = rels(type: :rates, dir: :incoming))
    ratings.count
  end

  def update_recommender_value
    self.recommender_value = self.get_popularity * self.get_standard_deviation_of_ratings
    self.save!
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(comment_params)
    @article = Article.find(params[:article_id])

    respond_to do |format|
      if @comment.save
        if params[:comment][:parent].nil?
        #this is not a nested comment
          @article = Article.find(params[:article_id])
          @article.comments << @comment
        else
          #this is a nested comment
          @parent = Comment.find(params[:comment][:parent])
          @parent.children << @comment
        end
        @comment.author = current_user

        format.html { redirect_to @article, notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { redirect_to @article, :flash => { :error => @comment.errors.full_messages.join(', ') } }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @article = Article.find(params[:article_id])
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to article_url(@article), notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_comment
    @comment = Comment.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def comment_params
    params.require(:comment).permit(:body, :pos_neg)
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_form.html.erb
<%= form_for [@article, @comment] do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', article_comments_path(@article) %>

app/views/comments/index.html.erb
<h1>Listing comments</h1>

<table>
  <thead>
    <tr>
      <th>Body</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.body %></td>
        <td><%= link_to 'Show', @article %></td>
        <td><%= link_to 'Edit', edit_article_comment_path(@article, comment) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New comment</h1>

<%= render 'form' %>

<%= link_to 'Back', article_comments_path(@article) %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Body:</strong>
  <%= @comment.body %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', article_comments_path(@article) %>