config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  resources :feedbacks

  get 'search/show'

  get 'profile/own' # must stand above the resources for profile
  post 'profile/search'
  post 'profile/contact'
  resources :profile

  get 'recommendations/show'

  devise_for :users

  get 'sessions/new', as: :login
  get 'sessions/destroy', as: :logout

  mount Mercury::Engine => '/'
  Mercury::Engine.routes

  post 'articles/search'
  resources :articles do
    member { put :mercury_update}
    member { post :rate }
    member { post :rate_comment }
    resources :comments
  end

end

app/controllers/recommendations_controller.rb
class RecommendationsController < ApplicationController
  def show
    unless user_signed_in?
      redirect_to new_user_session_path, notice: "You need to sign in to have access to personalized recommendations."
      return
    end
    # setup
    user_id = current_user.id

    # new users:
    new_user_article_query = Neo4j::Session.query.match("(me:User), (a:Article)")
      .where("NOT (me)--(a) AND me.uuid = '#{user_id}'").return("a").order("a.recommender_value desc").limit(15)
    @new_user_articles = new_user_article_query.to_a.collect{|arr| arr.a}

    #the following is only accurate for experienced users.

    # Users with lots of interaction
    #  MATCH (n:User) <--> (m) <--> (user:User) WHERE (n <> m AND n.uuid = '8f4e7dd7-d047-427f-8540-7102ef008529')
    # RETURN count(distinct m), user ORDER BY count(distinct m) DESC LIMIT {limit_21} | {"limit_21"=>21}
    interaction_query = Neo4j::Session.query.
        match("(me:User) <--> (m) <--> (other:User) <--> (profile:Profile)").
        where("me <> m AND me <> other AND me.uuid = '#{user_id}' AND profile.use_recommendations = true").
        return("count(distinct m) AS computed, other AS user").
        order("computed DESC").
        limit(5)
    @users = interaction_query.to_a

    # users with the same opinion (TODO: include the average rating of a user.)
    political_query = Neo4j::Session.query.
        match("(me:User) -[r1:`rates`]-> (a) <-[r2:`rates`]- (other:User) <--> (profile:Profile)").# a can be comment or article.
        where("me <> other AND me.uuid = '#{user_id}' AND profile.use_recommendations = true").
        with("(a.standard_deviation - ABS(r1.value - r2.value)) AS rating_diff, other").# ABS() = absolute value in cypher
        return("other as user, sum(rating_diff) AS computed").# other is the group key
        order("computed ASC").# The weighted rating difference should be small
        limit(5)
    @political_users = political_query.to_a


    political_users = @political_users.collect { |po| po.user }
    other_ids = Array.new
    political_users.each do |u|
      other_ids << u.id # add the user id to the query
    end

    # unread articles from my favourite political users
    article_query = Neo4j::Session.query.
        match("(me:User),(article:Article) <-[r2:`rates`]- (other:User)").
        where("NOT (me) -- (article) AND me.uuid = '#{user_id}' AND other.uuid IN #{other_ids}").
        return("article, percentileCont(r2.value, 0.5) AS computed").# percentileCont (x, 0.5 is the median)
        order("computed desc").limit(20)
    @articles = article_query.to_a

    opinion_factor = current_user.profile.discussion_preference
    discussion_factor = (100 - opinion_factor) / 100 # /100 because otherwise the opinion is practically useless
    combination_user_query = Neo4j::Session.query.
      match("(me:User) -[r1:`rates`]-> (m) <-[r2:`rates`]- (other:User) <--> (profile:Profile)").
      where("me <> m AND me <> other AND me.uuid = '#{user_id}' AND profile.use_recommendations = true").
      with("(m.standard_deviation - ABS(r1.value - r2.value)) AS rating_diff, other, m").
      return("(#{discussion_factor} * sum(rating_diff) - #{opinion_factor} * count(distinct m)) AS computed, other AS user").
      order("computed ASC").
      limit(10)

    @combination_users = combination_user_query.to_a

  end
end

app/helpers/recommendations_helper.rb
module RecommendationsHelper
end

app/views/recommendations/show.html.erb
<h1>Your Recommendations</h1>
<%= link_to "TUTORIAL", "#", id: "tutorial-button", class: "button alert expand" %>

<div class="row">
  <div class="small-12 medium-4 columns">
    <div id="firstStop" class="green-panel"><h4>Popular Articles</h4>
      Take a look and rate them. As this will greatly improve your recommendation accuracy.<br><br>
      <table>
        <thead>
        <tr>
          <th>Title</th>
          <th data-tooltip aria-haspopup="true" class="has-tip"
              title="log(Popularity) * Standard Deviation. This is a measurement over all articles and not personalized.
              Except for the fact that articles, with which the user actively interacted, are being omitted.">Computed
          </th>
        </tr>
        </thead>

        <tbody>
        <% @new_user_articles.each do |article| %>
            <tr>
              <td><%= link_to article.title, article, :class => '' %></td>
              <td><%= article.recommender_value.round(3) %></td>
            </tr>
        <% end %>
        </tbody>
      </table>
    </div>
  </div>

  <div class="small-12 medium-4 columns">
    <div id="middle-column" class="blue-panel"><h4>Recommended Articles</h4>
      You should enjoy reading these.
      <br>
      <br>
      <table>
        <thead>
        <tr>
          <th>Title</th>
          <th data-tooltip aria-haspopup="true" class="has-tip"
              title="This is based upon the articles which your favourite users rated highly.">Computed
          </th>
        </tr>
        </thead>

        <tbody>
        <% @articles.each do |art_comp| %>
            <tr>
              <td><%= link_to art_comp.article.title, art_comp.article %></td>
              <td><%= art_comp.computed %></td>
            </tr>
        <% end %>
        </tbody>
      </table>
    </div>
  </div>

  <div class="small-12 medium-4 columns">
    <div id="right-column" class="yellow-panel"><h4>Users</h4>
      Your recommended users: <br><br>
      <table>
        <thead>
        <tr>
          <th>Title</th>
          <th data-tooltip aria-haspopup="true" class="has-tip"
              title="This is a combination of recommended users based on your profile preference.">
            Computed
          </th>
        </tr>
        </thead>

        <tbody>
        <% @combination_users.each do |user_comp| %>
            <tr>
              <% profile = user_comp.user.profile %>
              <% if profile.nil? %>
                  <td><%= user_comp.user.username %></td>
              <% else %>
                  <td><%= link_to user_comp.user.username, profile_path(profile) %></td>
              <% end %>
              <td><%= user_comp.computed.round(3) %></td>
            </tr>
        <% end %>
        </tbody>
      </table>


      Ever thought about starting a <b>discussion group</b> with these people? <br><br>
      <table>
        <thead>
        <tr>
          <th>Title</th>
          <th data-tooltip aria-haspopup="true" class="has-tip"
              title="Upon how many items you interacted with these people.">Computed
          </th>
        </tr>
        </thead>

        <tbody>
        <% @users.each do |user_comp| %>
            <tr>
              <% profile = user_comp.user.profile %>
              <% if profile.nil? %>
                  <td><%= user_comp.user.username %></td>
              <% else %>
                  <td><%= link_to user_comp.user.username, profile_path(profile) %></td>
              <% end %>
              <td><%= user_comp.computed %></td>
            </tr>
        <% end %>
        </tbody>
      </table>
      Ever thought about starting a <b>activist group, community or political party</b> with these people?
      <br>
      <br>
      <table>
        <thead>
        <tr>
          <th>Title</th>
          <th data-tooltip aria-haspopup="true" class="has-tip"
              title="This denotes the difference of ratings upon specific items compared to the standard deviation of that item.
              The smaller this value, the better.">Weighted Rating Difference
          </th>
        </tr>
        </thead>

        <tbody>
        <% @political_users.each do |user_comp| %>
            <tr>
              <% profile = user_comp.user.profile %>
              <% if profile.nil? %>
                  <td><%= user_comp.user.username %></td>
              <% else %>
                  <td><%= link_to user_comp.user.username, profile_path(profile) %></td>
              <% end %>
              <td><%= user_comp.computed.round(3) %></td>
            </tr>
        <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>


<ol class="joyride-list" data-joyride>
  <li data-text="Next" data-options="tip_location: top; prev_button: false">
    <h4>Tutorial</h4>

    <p>This page is your personal recommendation page.
    </p>

    <p>
      They are based upon your active actions (comments, ratings, ...) which you do on this site.
      We do NOT measure every click, how long you look at content,
      facial expressions or any action which you perform on this site
      where it might not be obvious that you are expressing your opinion.
    </p>
  </li>
  <li data-id="firstStop" data-text="Next" data-prev-text="Prev" data-options="tip_location: right">
    <h4>New Here?</h4>

    <p>As a new user, you should probably start with these articles.<br>
      That way the items in the other columns will be more more accurate in the future.</p>
  </li>
  <li data-id="middle-column" data-class="custom so-awesome" data-text="Next" data-prev-text="Prev" data-options="tip_location: left">
    <h4>Interesting Stuff</h4>

    <p>As an experienced user, you should enjoy reading these articles.</p>
  </li>
  <li data-id="right-column" data-button="Next" data-prev-text="Prev" data-options="tip_location:left">
    <h4>Other Users</h4>

    <p>SmartParticipation wants to give you the opportunity to connect with other people of your liking.
      Both on- and offline. Try it out, send them a message.</p>
  </li>
  <li data-button="End" data-prev-text="Prev" data-options="tip_animation:fade">
    <h4>Enjoy!</h4>

    <p>:-)</p>
  </li>
</ol>