config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  resources :feedbacks

  get 'search/show'

  get 'profile/own' # must stand above the resources for profile
  post 'profile/search'
  post 'profile/contact'
  resources :profile

  get 'recommendations/show'

  devise_for :users

  get 'sessions/new', as: :login
  get 'sessions/destroy', as: :logout

  mount Mercury::Engine => '/'
  Mercury::Engine.routes

  post 'articles/search'
  resources :articles do
    member { put :mercury_update}
    member { post :rate }
    member { post :rate_comment }
    resources :comments
  end

end

app/views/layouts/_list_comments.html.erb
<!-- Show the comments -->
<% if @parent.nil? then
     comments = @article.comments.where(pos_neg: @filter_value)
   else
     comments = @parent.children
   end %>
<% comments.each do |comment| %>
    <div class="panel">
      <div class="row">
        <div class="small-12 medium-9 columns">
          <% author = comment.author %>
          <%= link_to(author.username.nil? ? "Anonymous" : author.username, author.profile) %> wrote <%= time_ago_in_words(comment.updated_at) %> ago:<br>
          <%= simple_format comment.body, class: 'strong' %>
        </div>
        <div class="small-12 medium-3 columns text-right">
          <div class="row">
            <div class="small-12 columns">
              <%= link_to "Rate this comment", '#', :class => 'button tiny expand rating', :data => {commentid: comment.id} %>
            </div>
          </div>
          <% if current_user == comment.author %>
              <div class="row">
                <div class="small-12 columns">
                  <%= link_to "Delete this comment", article_comment_path(@article, comment),
                              method: :delete, data: {confirm: 'Are you sure?'},
                              :class => 'button alert tiny expand' %>
                </div>
              </div>
          <% end %>
        </div>
      </div>
      <% if user_signed_in? %>
          <div class="row">
            <%= form_for [@article, Comment.new] do |f| %>
                <div class="small-9 columns"><%= f.text_area :body %>
                  <%= f.hidden_field :parent, value: comment.id %></div>
                <div class="small-3 columns"><%= f.submit "Reply", class: 'button small expand' %></div>
            <% end %>
          </div>
      <% end %>
      <div class="row commentarea" id="commentarea-<%= comment.id %>">
        <div class="small-12 columns commentRatingDiv" id="commentRatingDiv-<%= comment.id %>">
          <% if user_signed_in? %>
              <div class="row">
                <div class="small-9 columns">
                  <div class="range-slider commentRatingSlider" id="commentRatingSlider-<%= comment.id %>" data-slider data-options="display_selector: #commentRatingOutput-<%= comment.id %>;">
                    <span class="range-slider-handle" role="slider" tabindex="0"></span>
                    <span class="range-slider-active-segment"></span></div>
                </div>
                <div class="small-3 columns">
                  <%= form_tag @article.id + '/rate_comment', remote: true, class: 'rateCommentForm' do %>
                      <%= hidden_field_tag 'comment_rating' %>
                      <%= hidden_field_tag 'comment_id', comment.id %>
                      <%= submit_tag 'Rate', class: 'button expand commentSubmit', id: "submit-"+comment.id %>
                  <% end %>
                </div>
              </div>
              <div class="row">
                <div class="small-2 columns small-offset-5 text-center">
                  <span id="commentRatingOutput-<%= comment.id %>"></span>
                </div>
              </div>
          <% else %>
              <div class="blue-panel text-center">You need to log in in order to rate articles.</div>
          <% end %>
        </div>

      </div>
    </div>
      <% if comment.get_number_of_replies != 0 %>
        <div class="nested">
          <% @parent = comment %>
          <%= render "layouts/list_comments" %>
        </div>
      <% end %>
<% end %>

app/views/layouts/_navbar.html.erb
<div class="contain-to-grid">
  <nav class="top-bar" data-topbar role="navigation">
    <ul class="title-area">
      <li class="name"><h1><%= link_to 'SmartParticipation', root_path %></h1></li>
      <!-- Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone -->
      <li class="toggle-topbar menu-icon"><a href="#"><!--<span>Menu</span>--></a></li>
    </ul>
    <section class="top-bar-section">
      <!-- Left Nav Section -->
      <ul class="left">
        <li class=" <%= 'active' if params[:controller] == 'articles' %>">
          <%= link_to 'participate', articles_path %>
        </li>
        <li class=" <%= 'active' if params[:controller] == 'recommendations' %>">
          <%= link_to 'recommendations', recommendations_show_path %>
        </li>
        <li class=" <%= 'active' if params[:controller] == 'search' %>">
          <%= link_to 'search', search_show_path %>
        </li>
        <% if user_signed_in? %>
            <li class=" <%= 'active' if params[:controller] == 'feedbacks' %>">
              <%= link_to 'feedback', new_feedback_path %>
            </li>
        <% end %>
      </ul>
      <!-- Right Nav Section -->
      <ul class="right">
        <% if user_signed_in? %>
            <li class="has-form">
              <ul class="button-group">
                <li><%= link_to 'edit static profile', profile_own_path, class: 'button' %></li>
                <li><%= link_to 'logout', destroy_user_session_path, method: :delete, class: 'button' %></li>
              </ul>
            </li>
        <% else %>
            <li class="has-form">
              <ul class="button-group">
                <li><%= link_to 'register', new_user_registration_path, class: 'button' %></li>
                <li><%= link_to 'login', new_user_session_path, class: 'button' %></li>
              </ul>
            </li>
        <% end %>
      </ul>
    </section>
  </nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>

  <title><%= content_for?(:title) ? yield(:title) : 'SmartParticipation' %></title>

  <%= stylesheet_link_tag "application", media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag "vendor/modernizr" %>
  <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

</head>

<body>
<%= render '/layouts/navbar' %>


<div class="row">
  <div class="small-12 columns">
    <% if notice %>
        <div data-alert class="alert-box">
          <%= notice %>
          <a href="#" class="close">&times;</a>
        </div>
    <% end %>
    <% if alert || flash[:error] %>
        <div data-alert class="alert-box alert">
          <%= alert || flash[:error] %>
          <a href="#" class="close">&times;</a>
        </div>
    <% end %>

    <%= yield %>
  </div>
</div>
</body>
</html>

app/views/layouts/mercury.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, maximum-scale=1.0, initial-scale=1.0">
  <%= csrf_meta_tags %>
  <title>Editor</title>
  <%= stylesheet_link_tag    'mercury' %>
  <%= javascript_include_tag 'jquery-1.7', 'mercury', 'mercury_personal' %>
</head>
<body>
<script type="text/javascript">
    // Set to the url that you want to save any given page to, leave null for default handling.
    var saveUrl =  null;

    // Instantiate the PageEditor
    new Mercury.PageEditor(saveUrl, {
        saveStyle:  'form', // 'form', or 'json' (default json)
        saveMethod: 'PUT', // 'PUT', or 'POST', (create, vs. update -- default PUT)
        visible:    true  // boolean - if the interface should start visible or not
    });
</script>
</body>
</html>